version: "3.9"
services:
  bot:
    build: .
    volumes:
      - ./config.toml:/usr/src/tabby/config.toml
      - ./launch.py:/usr/src/tabby/launch.py
      - ./tabby:/usr/src/tabby/tabby
    secrets:
      - postgres-password
      - bot-token
    depends_on:
      - db
  db:
    image: postgres:15-bullseye
    environment:
      - POSTGRES_USER=tabby
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    expose:
      - 5432
    volumes:
      - ./tabby/schema.sql:/docker-entrypoint-initdb.d/tabby-schema.sql
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres-password
volumes:
  postgres-data:
    external: true
secrets:
  postgres-password:
    environment: TABBY_POSTGRES_PASSWORD
  bot-token:
    environment: TABBY_BOT_TOKEN
