# Note that this example assumes you're using Docker Compose.

[bot]
token = "${file:/run/secrets/bot-token}"
client_id = "${file:/run/secrets/client-id}"
client_secret = "${file:/run/secrets/client-secret}"

[database]
host = "db"
port = 5432
user = "tabby"
password = "${file:/run/secrets/postgres-password}"

[level]
xp_awards_before_cooldown = 1
xp_gain_cooldown = 60

[api]
host = "127.0.0.1"
port = 8080
secret_key = "MTIzNDU2NzgxMjM0NTY3ODEyMzQ1Njc4MTIzNDU2Nzg"

[limits]
webdrivers = 4
