# Note that this example assumes you're using Docker Compose.

[bot]
token = "${file:/run/secrets/tabby-bot-token}"

[database]
host = "db"
port = 5432
user = "tabby"
password = "${file:/run/secrets/tabby-postgres-password}"

[level]
xp_awards_before_cooldown = 1
xp_gain_cooldown = 60

[local_api]
host = "127.0.0.1"
port = 8080

[limits]
webdrivers = 4
